from typing import Any, Callable

class Flask:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def route(self, rule: str, **options: Any) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
    def run(self, *args: Any, **kwargs: Any) -> None: ...

class Response:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

__all__ = ['Flask', 'Response', 'jsonify', 'render_template_string']

def jsonify(*args: Any, **kwargs: Any) -> Any: ...
def render_template_string(source: str, **context: Any) -> str: ...
