// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: proto/detection.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BBox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	W             int32                  `protobuf:"varint,3,opt,name=w,proto3" json:"w,omitempty"`
	H             int32                  `protobuf:"varint,4,opt,name=h,proto3" json:"h,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BBox) Reset() {
	*x = BBox{}
	mi := &file_proto_detection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BBox) ProtoMessage() {}

func (x *BBox) ProtoReflect() protoreflect.Message {
	mi := &file_proto_detection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BBox.ProtoReflect.Descriptor instead.
func (*BBox) Descriptor() ([]byte, []int) {
	return file_proto_detection_proto_rawDescGZIP(), []int{0}
}

func (x *BBox) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *BBox) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *BBox) GetW() int32 {
	if x != nil {
		return x.W
	}
	return 0
}

func (x *BBox) GetH() int32 {
	if x != nil {
		return x.H
	}
	return 0
}

type Detection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bbox          *BBox                  `protobuf:"bytes,1,opt,name=bbox,proto3" json:"bbox,omitempty"`
	Confidence    float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	ClassId       int32                  `protobuf:"varint,3,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	Label         string                 `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Detection) Reset() {
	*x = Detection{}
	mi := &file_proto_detection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detection) ProtoMessage() {}

func (x *Detection) ProtoReflect() protoreflect.Message {
	mi := &file_proto_detection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detection.ProtoReflect.Descriptor instead.
func (*Detection) Descriptor() ([]byte, []int) {
	return file_proto_detection_proto_rawDescGZIP(), []int{1}
}

func (x *Detection) GetBbox() *BBox {
	if x != nil {
		return x.Bbox
	}
	return nil
}

func (x *Detection) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Detection) GetClassId() int32 {
	if x != nil {
		return x.ClassId
	}
	return 0
}

func (x *Detection) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type DetectionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FrameNumber   uint64                 `protobuf:"varint,1,opt,name=frame_number,json=frameNumber,proto3" json:"frame_number,omitempty"`
	Timestamp     float64                `protobuf:"fixed64,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Detections    []*Detection           `protobuf:"bytes,3,rep,name=detections,proto3" json:"detections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectionEvent) Reset() {
	*x = DetectionEvent{}
	mi := &file_proto_detection_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionEvent) ProtoMessage() {}

func (x *DetectionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_detection_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectionEvent.ProtoReflect.Descriptor instead.
func (*DetectionEvent) Descriptor() ([]byte, []int) {
	return file_proto_detection_proto_rawDescGZIP(), []int{2}
}

func (x *DetectionEvent) GetFrameNumber() uint64 {
	if x != nil {
		return x.FrameNumber
	}
	return 0
}

func (x *DetectionEvent) GetTimestamp() float64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DetectionEvent) GetDetections() []*Detection {
	if x != nil {
		return x.Detections
	}
	return nil
}

var File_proto_detection_proto protoreflect.FileDescriptor

const file_proto_detection_proto_rawDesc = "" +
	"\n" +
	"\x15proto/detection.proto\x12\tpetcamera\">\n" +
	"\x04BBox\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\f\n" +
	"\x01w\x18\x03 \x01(\x05R\x01w\x12\f\n" +
	"\x01h\x18\x04 \x01(\x05R\x01h\"\x81\x01\n" +
	"\tDetection\x12#\n" +
	"\x04bbox\x18\x01 \x01(\v2\x0f.petcamera.BBoxR\x04bbox\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12\x19\n" +
	"\bclass_id\x18\x03 \x01(\x05R\aclassId\x12\x14\n" +
	"\x05label\x18\x04 \x01(\tR\x05label\"\x87\x01\n" +
	"\x0eDetectionEvent\x12!\n" +
	"\fframe_number\x18\x01 \x01(\x04R\vframeNumber\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x01R\ttimestamp\x124\n" +
	"\n" +
	"detections\x18\x03 \x03(\v2\x14.petcamera.DetectionR\n" +
	"detectionsBFZDgithub.com/dj-oyu/rdk-x5_smart-pet-camera/streaming-server/pkg/protob\x06proto3"

var (
	file_proto_detection_proto_rawDescOnce sync.Once
	file_proto_detection_proto_rawDescData []byte
)

func file_proto_detection_proto_rawDescGZIP() []byte {
	file_proto_detection_proto_rawDescOnce.Do(func() {
		file_proto_detection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_detection_proto_rawDesc), len(file_proto_detection_proto_rawDesc)))
	})
	return file_proto_detection_proto_rawDescData
}

var file_proto_detection_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_detection_proto_goTypes = []any{
	(*BBox)(nil),           // 0: petcamera.BBox
	(*Detection)(nil),      // 1: petcamera.Detection
	(*DetectionEvent)(nil), // 2: petcamera.DetectionEvent
}
var file_proto_detection_proto_depIdxs = []int32{
	0, // 0: petcamera.Detection.bbox:type_name -> petcamera.BBox
	1, // 1: petcamera.DetectionEvent.detections:type_name -> petcamera.Detection
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_detection_proto_init() }
func file_proto_detection_proto_init() {
	if File_proto_detection_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_detection_proto_rawDesc), len(file_proto_detection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_detection_proto_goTypes,
		DependencyIndexes: file_proto_detection_proto_depIdxs,
		MessageInfos:      file_proto_detection_proto_msgTypes,
	}.Build()
	File_proto_detection_proto = out.File
	file_proto_detection_proto_goTypes = nil
	file_proto_detection_proto_depIdxs = nil
}
