#!/usr/bin/env bash
set -euo pipefail

# Test script to verify semaphore signaling between Python detector and Go server
# This script checks that sem_post in Python detector triggers sem_wait in Go broadcaster

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

echo "==================================="
echo "Semaphore Signaling Verification"
echo "==================================="
echo ""
echo "This test verifies that:"
echo "1. Python detector posts semaphore (sem_post) when writing detections"
echo "2. Go DetectionBroadcaster receives semaphore signal (sem_wait)"
echo "3. Event-driven architecture is working (no polling)"
echo ""
echo "Test procedure:"
echo "1. Run the system with DEBUG log level: ./scripts/run_camera_switcher_yolo_streaming.sh --log-level debug"
echo "2. Wait for a few detections to occur"
echo "3. Check logs for evidence of semaphore signaling"
echo ""
echo "Expected log patterns:"
echo ""
echo "[Python side - /tmp/yolo_detector.log]:"
echo "  DEBUG:RealSharedMemory:sem_post SUCCESS: frame=X, num_det=Y, version=Z"
echo ""
echo "[Go side - /tmp/web_monitor.log]:"
echo "  [DEBUG] [DetectionBroadcaster] Client subscribed/unsubscribed messages"
echo "  No 'timeout' or 'semaphore wait failed' errors"
echo ""
echo "If semaphore signaling is working correctly, you should see:"
echo "- Regular sem_post SUCCESS messages in yolo_detector.log"
echo "- No semaphore timeout errors in web_monitor.log"
echo "- Detection events appear in browser immediately (no delay)"
echo ""
echo "To run full system test:"
echo "  cd ${REPO_ROOT}"
echo "  ./scripts/run_camera_switcher_yolo_streaming.sh --log-level debug"
echo ""
echo "To check logs after running:"
echo "  grep 'sem_post' /tmp/yolo_detector.log | head -20"
echo "  grep -i 'semaphore\\|timeout' /tmp/web_monitor.log | head -20"
echo ""
